(() => {
  const games = {
    pong: { title: "Pong", help: "Move with ↑ and ↓, or drag on the court." },
    breakout: { title: "Breakout", help: "Move with ← and →, or drag the paddle." },
    asteroids: { title: "Asteroids", help: "Turn with ← and →, thrust with ↑, fire with Space." },
    minesweeper: { title: "Minesweeper", help: "Reveal every safe tile. Long-press or right-click to flag." },
    connect4: { title: "Connect Four", help: "Two players take turns. Connect four discs to win." },
    memory: { title: "Memory Match", help: "Turn over two tiles at a time and find all eight pairs." },
    invaders: { title: "Invaders", help: "Move with ← and → and fire with Space." }
  };
  const canvas = document.getElementById("canvas"), ctx = canvas.getContext("2d"), board = document.getElementById("board"), scoreEl = document.getElementById("score"), scoreLabel = document.getElementById("scoreLabel"), title = document.getElementById("gameTitle"), instructions = document.getElementById("instructions"), picker = document.getElementById("gamePicker"), message = document.getElementById("message"), touchControls = document.getElementById("touchControls");
  let current, cleanup = () => {}, keys = new Set();
  const score = value => scoreEl.textContent = value;
  const rand = (min,max) => Math.random()*(max-min)+min;
  function finish(text){message.hidden=false;message.querySelector("strong").textContent=text}
  function frame(setup,update,draw){let state=setup(),last=performance.now(),raf;function loop(now){const dt=Math.min((now-last)/1000,.04);last=now;update(state,dt);draw(state);raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)}
  function canvasPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}}
  function paintBase(){ctx.fillStyle="#08090c";ctx.fillRect(0,0,800,520);ctx.strokeStyle="#242933";ctx.lineWidth=2}

  function pong(){let playerY=190;const move=e=>playerY=Math.max(0,Math.min(400,canvasPoint(e).y-60));canvas.addEventListener("pointermove",move);const stop=frame(()=>({ball:{x:400,y:260,vx:330,vy:rand(-190,190)},ai:190,p:0,a:0}), (s,dt)=>{if(keys.has("ArrowUp"))playerY-=360*dt;if(keys.has("ArrowDown"))playerY+=360*dt;playerY=Math.max(0,Math.min(400,playerY));s.ai+=Math.sign(s.ball.y-s.ai-60)*250*dt;s.ai=Math.max(0,Math.min(400,s.ai));s.ball.x+=s.ball.vx*dt;s.ball.y+=s.ball.vy*dt;if(s.ball.y<12||s.ball.y>508){s.ball.vy*=-1;s.ball.y=Math.max(12,Math.min(508,s.ball.y))}if(s.ball.vx<0&&s.ball.x<55&&s.ball.x>30&&s.ball.y>playerY&&s.ball.y<playerY+120){s.ball.vx=Math.abs(s.ball.vx)*1.04;s.ball.vy+=(s.ball.y-playerY-60)*3}if(s.ball.vx>0&&s.ball.x>745&&s.ball.x<770&&s.ball.y>s.ai&&s.ball.y<s.ai+120)s.ball.vx=-Math.abs(s.ball.vx)*1.04;if(s.ball.x<0||s.ball.x>800){s.ball.x<0?s.a++:s.p++;score(`${s.p} — ${s.a}`);s.ball={x:400,y:260,vx:s.ball.x<0?330:-330,vy:rand(-190,190)}}},s=>{paintBase();ctx.setLineDash([14,14]);ctx.beginPath();ctx.moveTo(400,0);ctx.lineTo(400,520);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#f5f7fa";ctx.fillRect(30,playerY,18,120);ctx.fillStyle="#d8ff45";ctx.fillRect(752,s.ai,18,120);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(s.ball.x,s.ball.y,11,0,Math.PI*2);ctx.fill()});return()=>{stop();canvas.removeEventListener("pointermove",move)}}
  function breakout(){let paddle=320;const move=e=>paddle=Math.max(0,Math.min(640,canvasPoint(e).x-80));canvas.addEventListener("pointermove",move);const stop=frame(()=>({ball:{x:400,y:390,vx:210,vy:-260},bricks:Array.from({length:40},(_,i)=>({x:42+(i%8)*91,y:50+Math.floor(i/8)*42,on:true})),points:0}), (s,dt)=>{if(keys.has("ArrowLeft"))paddle-=430*dt;if(keys.has("ArrowRight"))paddle+=430*dt;paddle=Math.max(0,Math.min(640,paddle));let b=s.ball;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<10||b.x>790)b.vx*=-1;if(b.y<10)b.vy=Math.abs(b.vy);if(b.y>475&&b.y<500&&b.x>paddle&&b.x<paddle+160)b.vy=-Math.abs(b.vy);for(const brick of s.bricks)if(brick.on&&b.x>brick.x&&b.x<brick.x+81&&b.y>brick.y&&b.y<brick.y+31){brick.on=false;b.vy*=-1;s.points+=10;score(s.points);break}if(!s.bricks.some(x=>x.on))finish("You cleared the wall!");if(b.y>540){b.x=400;b.y=390;b.vy=-260;s.points=Math.max(0,s.points-20);score(s.points)}},s=>{paintBase();for(const [i,b] of s.bricks.entries())if(b.on){ctx.fillStyle=i<16?"#d8ff45":"#ff727c";ctx.fillRect(b.x,b.y,81,31)}ctx.fillStyle="#f5f7fa";ctx.fillRect(paddle,485,160,18);ctx.beginPath();ctx.arc(s.ball.x,s.ball.y,10,0,Math.PI*2);ctx.fill()});return()=>{stop();canvas.removeEventListener("pointermove",move)}}
  function asteroids(){const stop=frame(()=>({ship:{x:400,y:260,a:-Math.PI/2,vx:0,vy:0},rocks:Array.from({length:7},()=>({x:rand(0,800),y:rand(0,520),vx:rand(-70,70),vy:rand(-70,70),r:rand(20,44)})),shots:[],points:0,cool:0}), (s,dt)=>{const p=s.ship;if(keys.has("ArrowLeft"))p.a-=3.6*dt;if(keys.has("ArrowRight"))p.a+=3.6*dt;if(keys.has("ArrowUp")){p.vx+=Math.cos(p.a)*180*dt;p.vy+=Math.sin(p.a)*180*dt}p.x=(p.x+p.vx*dt+800)%800;p.y=(p.y+p.vy*dt+520)%520;p.vx*=.995;p.vy*=.995;s.cool-=dt;if(keys.has(" ")&&s.cool<=0){s.shots.push({x:p.x,y:p.y,vx:Math.cos(p.a)*440,vy:Math.sin(p.a)*440,life:1.2});s.cool=.2}for(const o of [...s.rocks,...s.shots]){o.x=(o.x+o.vx*dt+800)%800;o.y=(o.y+o.vy*dt+520)%520}s.shots.forEach(x=>x.life-=dt);s.shots=s.shots.filter(x=>x.life>0);for(const shot of s.shots)for(const rock of s.rocks)if(Math.hypot(shot.x-rock.x,shot.y-rock.y)<rock.r){rock.r=0;shot.life=0;s.points+=25;score(s.points)}s.rocks=s.rocks.filter(x=>x.r);while(s.rocks.length<7)s.rocks.push({x:rand(0,800),y:rand(0,520),vx:rand(-80,80),vy:rand(-80,80),r:rand(20,44)})},s=>{paintBase();ctx.strokeStyle="#8ea1b5";for(const r of s.rocks){ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,rr=r.r*(i%2?.75:1);const x=r.x+Math.cos(a)*rr,y=r.y+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}ctx.fillStyle="#d8ff45";for(const b of s.shots)ctx.fillRect(b.x-2,b.y-2,4,4);const p=s.ship;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.beginPath();ctx.moveTo(20,0);ctx.lineTo(-15,13);ctx.lineTo(-8,0);ctx.lineTo(-15,-13);ctx.closePath();ctx.strokeStyle="#f5f7fa";ctx.stroke();ctx.restore()});return stop}
  function invaders(){let shipX=365;const move=e=>shipX=Math.max(0,Math.min(730,canvasPoint(e).x-35));canvas.addEventListener("pointermove",move);const stop=frame(()=>({enemies:Array.from({length:32},(_,i)=>({x:100+(i%8)*75,y:65+Math.floor(i/8)*55,on:true})),shots:[],enemyShots:[],dir:1,cool:0,points:0}), (s,dt)=>{if(keys.has("ArrowLeft"))shipX-=400*dt;if(keys.has("ArrowRight"))shipX+=400*dt;shipX=Math.max(0,Math.min(730,shipX));s.cool-=dt;if(keys.has(" ")&&s.cool<=0){s.shots.push({x:shipX+35,y:450});s.cool=.24}const live=s.enemies.filter(e=>e.on);if(live.some(e=>e.x>740)||live.some(e=>e.x<20)){s.dir*=-1;live.forEach(e=>e.y+=16)}live.forEach(e=>e.x+=s.dir*35*dt);s.shots.forEach(b=>b.y-=420*dt);s.shots=s.shots.filter(b=>b.y>-10);for(const b of s.shots)for(const e of live)if(Math.abs(b.x-e.x)<25&&Math.abs(b.y-e.y)<20){e.on=false;b.y=-20;s.points+=10;score(s.points)}if(!s.enemies.some(e=>e.on))finish("Wave cleared!");if(live.some(e=>e.y>420))finish("The invaders landed")},s=>{paintBase();ctx.fillStyle="#d8ff45";for(const e of s.enemies)if(e.on){ctx.fillRect(e.x-20,e.y-12,40,24);ctx.clearRect(e.x-10,e.y-4,6,6);ctx.clearRect(e.x+5,e.y-4,6,6)}ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(shipX,480);ctx.lineTo(shipX+35,445);ctx.lineTo(shipX+70,480);ctx.closePath();ctx.fill();ctx.fillStyle="#ff727c";for(const b of s.shots)ctx.fillRect(b.x-2,b.y,4,15)});return()=>{stop();canvas.removeEventListener("pointermove",move)}}
  function minesweeper(){const size=9,mines=10,cells=Array(size*size).fill(0).map((_,i)=>({i,mine:false,revealed:false,flag:false}));for(let n=0;n<mines;){const i=Math.floor(Math.random()*cells.length);if(!cells[i].mine){cells[i].mine=true;n++}}const around=i=>{const r=Math.floor(i/size),c=i%size;return cells.filter(x=>{const rr=Math.floor(x.i/size),cc=x.i%size;return Math.abs(rr-r)<=1&&Math.abs(cc-c)<=1&&x.i!==i})};const toggleFlag=cell=>{if(cell.revealed)return;cell.flag=!cell.flag;render()};const reveal=cell=>{if(cell.flag||cell.revealed)return;cell.revealed=true;if(cell.mine){render();finish("Mine hit");return}if(!around(cell.i).filter(x=>x.mine).length)around(cell.i).forEach(reveal);render();if(cells.filter(x=>!x.mine).every(x=>x.revealed))finish("Field cleared!")};function render(){board.replaceChildren(...cells.map(cell=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",cell.flag?"Flagged tile":cell.revealed?"Revealed tile":"Hidden tile");if(cell.revealed){b.className="revealed";const n=around(cell.i).filter(x=>x.mine).length;b.textContent=cell.mine?"●":n||""}else b.textContent=cell.flag?"⚑":"";let holdTimer,longPressed=false;b.onclick=()=>{if(!longPressed)reveal(cell)};b.onpointerdown=e=>{if(e.pointerType==="mouse")return;longPressed=false;holdTimer=setTimeout(()=>{longPressed=true;toggleFlag(cell)},550)};const clearHold=()=>clearTimeout(holdTimer);b.onpointerup=clearHold;b.onpointercancel=clearHold;b.onpointerleave=clearHold;b.oncontextmenu=e=>{e.preventDefault();toggleFlag(cell)};return b}));score(cells.filter(x=>x.revealed&&!x.mine).length)}board.style.gridTemplateColumns=`repeat(${size},1fr)`;render();return()=>{}}
  function connect4(){const cells=Array(42).fill(0),wins=[[1,0],[0,1],[1,1],[1,-1]];let player=1,ended=false;function hasWon(i){const r=Math.floor(i/7),c=i%7;return wins.some(([dr,dc])=>{let n=1;for(const sign of [-1,1])for(let k=1;k<4;k++){const rr=r+dr*k*sign,cc=c+dc*k*sign;if(rr<0||rr>=6||cc<0||cc>=7||cells[rr*7+cc]!==player)break;n++}return n>=4})}function play(col){if(ended)return;for(let row=5;row>=0;row--){const i=row*7+col;if(!cells[i]){cells[i]=player;if(hasWon(i)){ended=true;render();finish(`Player ${player} wins!`);return}player=player===1?2:1;score(`Player ${player}`);render();return}}}function render(){board.replaceChildren(...cells.map((value,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",`Column ${(i%7)+1}`+(value?`, player ${value}`:""));if(value)b.className=value===1?"player-one":"player-two";b.onclick=()=>play(i%7);return b}))}board.style.gridTemplateColumns="repeat(7,1fr)";score("Player 1");render();return()=>{}}
  function memory(){const icons=["◆","●","▲","■","★","✦","⬟","♥"],cells=[...icons,...icons].sort(()=>Math.random()-.5).map((icon,i)=>({i,icon,open:false,matched:false}));let picks=[],moves=0,locked=false;function pick(cell){if(locked||cell.open||cell.matched)return;cell.open=true;picks.push(cell);render();if(picks.length===2){moves++;score(moves);if(picks[0].icon===picks[1].icon){picks.forEach(x=>x.matched=true);picks=[];if(cells.every(x=>x.matched))finish(`Cleared in ${moves} moves`);render()}else{locked=true;setTimeout(()=>{picks.forEach(x=>x.open=false);picks=[];locked=false;render()},650)}}}function render(){board.replaceChildren(...cells.map(cell=>{const b=document.createElement("button");b.type="button";b.textContent=cell.open||cell.matched?cell.icon:"?";if(cell.matched)b.className="matched";b.onclick=()=>pick(cell);return b}))}board.style.gridTemplateColumns="repeat(4,1fr)";render();return()=>{}}
  const starters={pong,breakout,asteroids,minesweeper,connect4,memory,invaders};
  function start(name){cleanup();current=games[name]?name:"pong";history.replaceState(null,"",`?game=${current}`);title.textContent=games[current].title;instructions.textContent=games[current].help;scoreLabel.textContent=current==="connect4"?"Turn":current==="memory"?"Moves":"Score";score(0);message.hidden=true;canvas.hidden=["minesweeper","connect4","memory"].includes(current);board.hidden=!canvas.hidden;touchControls.hidden=canvas.hidden;touchControls.style.display=canvas.hidden?"none":"";picker.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.game===current));cleanup=starters[current]();if(!canvas.hidden)canvas.focus()}
  for(const [name,game] of Object.entries(games)){const b=document.createElement("button");b.type="button";b.dataset.game=name;b.textContent=game.title;b.onclick=()=>start(name);picker.appendChild(b)}
  addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key)){e.preventDefault();keys.add(e.key)}});addEventListener("keyup",e=>keys.delete(e.key));document.querySelectorAll("[data-key]").forEach(b=>{const key=b.dataset.key;const down=e=>{e.preventDefault();keys.add(key)},up=e=>{e.preventDefault();keys.delete(key)};b.addEventListener("pointerdown",down);b.addEventListener("pointerup",up);b.addEventListener("pointercancel",up)});document.getElementById("restart").onclick=()=>start(current);message.querySelector("button").onclick=()=>start(current);start(new URLSearchParams(location.search).get("game")||"pong");
})();
