(() => {
  const CATALOG_PATH="/storage/json/games.json", CACHE_KEY="nexus-games-cache-v2";
  const grid=document.getElementById("gameGrid"),status=document.getElementById("libraryStatus"),count=document.getElementById("gamesTitle"),search=document.getElementById("gameSearch"),random=document.getElementById("random-button"),empty=document.getElementById("emptyState"),filters=[...document.querySelectorAll("[data-filter]")];
  let games=[],visibleGames=[],activeFilter="all";
  const categoryRules={classic:/2048|asteroids|breakout|connect four|doom|invaders|minesweeper|pacman|pong|snake|super mario|memory match|pinball|solitaire|sudoku|sokoban|moon lander/i,sports:/basket|boxing|football|mario kart|racing|racer|retro bowl|soccer|speed|volley|golf|hockey|billiards/i,adventure:/animal crossing|dadish|deltarune|duck life|hollow knight|mario|pikuniku|pok[eé]mon|sonic|undertale|zelda|delver/i,shooter:/counter-strike|shooter|tank arena|thunder vanguard|shell shock|sniper|kirka|krunker|ev\\.io/i,arcade:/angry birds|bacon|burrito|cluster|cookie|crossy|doodle|fancy|geometry|run |slope|subway|vex|tunnel|arcade|sling|fruit slice/i};
  function normalizeGame(game,index){const title=String(game.title||game.alt||`Game ${index+1}`).trim(),declared=String(game.genre||"").toLowerCase(),categories=Object.entries(categoryRules).filter(([name,pattern])=>declared===name||pattern.test(title)).map(([name])=>name);return{title,alt:String(game.alt||title),url:String(game.url||""),img:String(game.img||""),category:declared||categories[0]||"games",categories}}
  const initials=title=>title.split(/\s+/).slice(0,2).map(word=>word[0]).join("").toUpperCase();
  function createCard(game,index){const article=document.createElement("article");article.className="game-card";article.style.setProperty("--order",index);article.style.setProperty("--cover-hue",[68,156,205,262,328][game.title.length%5]);article.dataset.title=game.title.toLowerCase();article.dataset.categories=game.categories.join(" ");const link=document.createElement("a");link.href=game.url;link.setAttribute("aria-label",`Play ${game.title}`);const art=document.createElement("div");art.className="game-art";const fallback=document.createElement("span");fallback.className="fallback-art";fallback.textContent=initials(game.title);fallback.setAttribute("aria-hidden","true");art.append(fallback);if(game.img){const image=document.createElement("img");image.src=game.img;image.alt=game.alt;image.loading=index<12?"eager":"lazy";image.decoding="async";image.addEventListener("load",()=>image.classList.add("is-loaded"),{once:true});image.addEventListener("error",()=>image.remove(),{once:true});art.append(image)}const play=document.createElement("span");play.className="play-mark";play.setAttribute("aria-hidden","true");play.innerHTML='<svg viewBox="0 0 24 24"><path d="m9 6 9 6-9 6Z"/></svg>';art.append(play);const title=document.createElement("h2");title.textContent=game.title;const category=document.createElement("p");category.textContent=game.category;link.append(art,title,category);article.append(link);return article}
  function render(){grid.replaceChildren(...games.map(createCard));grid.querySelectorAll("img").forEach(image=>{if(image.complete&&image.naturalWidth)image.classList.add("is-loaded")});applyFilters();random.disabled=!games.length;status.hidden=true}
  function applyFilters(){const query=search.value.trim().toLowerCase(),cards=[...grid.querySelectorAll(".game-card")];visibleGames=[];cards.forEach((card,index)=>{const visible=card.dataset.title.includes(query)&&(activeFilter==="all"||card.dataset.categories.split(" ").includes(activeFilter));card.hidden=!visible;if(visible)visibleGames.push({game:games[index],card})});const total=games.length,shown=visibleGames.length;count.textContent=query||activeFilter!=="all"?`${shown} of ${total} games shown`:`${total} games ready to play`;empty.hidden=shown!==0}
  function setGames(data){games=data.map(normalizeGame).filter(game=>game.title&&game.url);games.sort((a,b)=>a.title.localeCompare(b.title));render()}
  async function loadGames(){try{const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(Array.isArray(cached))setGames(cached)}catch{localStorage.removeItem(CACHE_KEY)}try{const response=await fetch(CATALOG_PATH,{cache:"no-store"});if(!response.ok)throw new Error(`Catalog request returned ${response.status}`);const fresh=await response.json();if(!Array.isArray(fresh))throw new Error("Catalog data is not a list");localStorage.setItem(CACHE_KEY,JSON.stringify(fresh));setGames(fresh)}catch(error){if(!games.length){status.replaceChildren();const strong=document.createElement("strong"),detail=document.createElement("span"),retry=document.createElement("button");strong.textContent="Could not load the game library.";detail.textContent=error.message;retry.type="button";retry.textContent="Try again";retry.onclick=()=>location.reload();status.append(strong,detail,retry);status.classList.add("is-error")}}}
  search.addEventListener("input",applyFilters);filters.forEach(button=>button.addEventListener("click",()=>{activeFilter=button.dataset.filter;filters.forEach(item=>{const active=item===button;item.classList.toggle("is-active",active);item.setAttribute("aria-pressed",active)});applyFilters()}));random.addEventListener("click",()=>{if(visibleGames.length)location.href=visibleGames[Math.floor(Math.random()*visibleGames.length)].game.url});document.getElementById("clearSearch").addEventListener("click",()=>{search.value="";filters[0].click();search.focus()});document.addEventListener("keydown",event=>{if(event.key==="/"&&document.activeElement!==search){event.preventDefault();search.focus()}});loadGames();
})();
